databases:
  - name: foodiary_DB
    databaseName: foodiary_db
    user: foodiary
    region: singapore

services:
  - type: web
    name: foodiary
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: foodiary
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false