databases:
  - name: foodiary_DB
    databaseName: foodiary_db
    user: foodiary
    region: singapore

services:
  - type: web
    name: foodiary
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: foodiary_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false